os: linux
dist: xenial
language: shell
jobs:
  include:
    - arch: ppc64le
      os: linux
      dist: focal
      language: shell
      virt: lxd
      script: true
      
    - arch: s390x
      os: linux
      dist: focal
      language: shell
      virt: lxd
      script: true
      
    - arch: arm64-graviton2
      os: linux
      dist: focal
      language: shell
      virt: lxd
      script: true

    - arch: arm64
      os: linux
      dist: focal
      language: shell
      virt: lxd
      script: true
    
    - arch: amd64
      os: linux
      dist: focal
      language: shell
      virt: lxd
      script: true
