language: python
cache:
  - $HOME/.m2
jobs:
  include:
    - os: linux
      dist: focal
      arch: ppc64le
      before_install:
        - sudo apt-get -yq install maven
      script: true
      
    - os: linux
      dist: focal
      arch: s390x
      before_install:
        - sudo apt-get -yq install maven
      script: true
      
    - os: linux
      dist: focal
      arch: arm64-graviton2
      before_install:
        - sudo apt-get -yq install maven
      script: true
      
    - os: linux
      dist: focal
      arch: arm64
      before_install:
        - sudo apt-get -yq install maven
      script: true
      
    - os: linux
      dist: focal
      arch: amd64
      before_install:
        - sudo apt-get -yq install maven
      script: true
