jobs:
  include:
    - os: linux
      dist: xenial
      arch: ppc64le
      script: true
      
    - os: linux
      dist: xenial
      arch: s390x
      script: true
      
    - os: linux
      dist: xenial
      arch: arm64-graviton2
      script: true
      
    - os: linux
      dist: xenial
      arch: arm64
      script: true
      
    - os: linux
      dist: xenial
      arch: amd64
      script: true
