os: linux
dist: xenial
language: ruby
jobs:
  include:
    - arch: ppc64le
      os: linux
      dist: bionic
      language: shell
      before_install:
        - git version
        - sudo add-apt-repository -y ppa:git-core/ppa
        - sudo apt-get update
        - sudo apt-get -y install git
      script:
        - git version
      
    - arch: arm64-graviton2
      os: linux
      dist: focal
      language: shell
      virt: lxd
      script: true
