os: linux
dist: xenial
language: java
jdk: openjdk11
before_install:
  - sudo systemctl stop epmd.socket epmd.service
jobs:
  include:
    - arch: ppc64le
      script: true
      
    - arch: s390x
      script: true
      
    - arch: arm64-graviton2
      script: true
      
    - arch: arm64
      script: true
      
    - arch: amd64
      script: true
