os: linux
dist: xenial
language: java
jdk: openjdk11
cache:
  directories:
    - ~/.m2
addons:
  apt:
    packages:
      - maven
jobs:
  include:
    - arch: ppc64le
      script: true
      
    - arch: s390x
      script: true
      
    - arch: arm64-graviton2
      script: true

    - arch: arm64
      script: true
      
    - arch: amd64
      script: true
